### ISSUE TITLE
BunsenLabs jgmenu crashes without xsel

### ISSUE THREAD

**Issue by hhhorb** [jgmenu/jgmenu#202] opened 2023-07-03 20:17 UTC
Hey!

I just discovered that if the Debian package xsel is not present, opening jgmenu>Utilities>Take Screenshot>* crashes the desktop.

Hope all is well!

**Comment by johanmalm** [comment] 2023-07-03 20:34
Hi there. I'm good thanks. Trust all is good with you too.
Let me have a look.

**Comment by johanmalm** [comment] 2023-07-03 20:38
I've been running pure Wayland for a while now with `wlroots` which is hard (for me anyway) to do on Debian. In other words, I haven't got a test bed.

Looks like that menu entry just calls `bl-scrot-pipemenu`. What happens if you just run that command in a terminal?

Ref: https://github.com/BunsenLabs/bunsen-configs/blob/3adc206701b346d22db952cbdeda7284c96752f3/skel/.config/jgmenu/prepend.csv#L41

**Comment by hhhorb** [comment] 2023-07-03 20:46
`ash@weyland-yutani:~$ bl-scrot-pipemenu

Warning: Failed to source /home/ash/.config/image-upload/imgur/credentials.conf in /home/ash/.config/image-upload/imgur/

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6085:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6089:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6089:55: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6093:35: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6103:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6103:75: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6103:114: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6103:152: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6109:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6109:91: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6118:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6122:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6122:55: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6126:35: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6136:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6136:75: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6136:114: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6136:152: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6142:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(yad:2481): Gtk-WARNING **: 16:41:05.128: Theme parsing error: gtk.css:6142:91: The :insensitive pseudo-class is deprecated. Use :disabled instead.
"""Xfce4 Screenshooter""","""xfce4-screenshooter"""
"""scrot Screenshooter""",^checkout(takescrot)
"""Imgur - Upload Screenshot""",^checkout(imgur)

^tag(imgur_acct)
Back,^back()
"""screenshot Now""","""bl-imgur-upload -l"""
"""screenshot In 5 secs...""","""bl-imgur-upload -l -d 5"""
"""screenshot In 10 secs...""","""bl-imgur-upload -l -d 10"""
"""screenshot Select Area""","""bl-imgur-upload -l -s"""
"""screenshot Current Window""","""bl-imgur-upload -l -w"""

^tag(imgur_anon)
Back,^back()
"""screenshot Now""","""bl-imgur-upload"""
"""screenshot In 5 secs...""","""bl-imgur-upload -d 5"""
"""screenshot In 10 secs...""","""bl-imgur-upload -d 10"""
"""screenshot Select Area""","""bl-imgur-upload -s"""
"""screenshot Current Window""","""bl-imgur-upload -w"""

^tag(takescrot)
Back,^back()
"""scrot Now""","""scrot /home/ash/Pictures/screenshots/%F-%H-%M-%S_scrot.png -e 'bl-image-viewer /home/ash/Pictures/screenshots/%F-%H-%M-%S_scrot.png'"""
"""scrot In 5 secs...""","""scrot -d 5 /home/ash/Pictures/screenshots/%F-%H-%M-%S_scrot.png -e 'bl-image-viewer /home/ash/Pictures/screenshots/%F-%H-%M-%S_scrot.png'"""
"""scrot In 10 secs...""","""scrot -d 10 /home/ash/Pictures/screenshots/%F-%H-%M-%S_scrot.png -e 'bl-image-viewer /home/ash/Pictures/screenshots/%F-%H-%M-%S_scrot.png'"""
"""scrot Select Area""","""scrot -s /home/ash/Pictures/screenshots/%F-%H-%M-%S_scrot.png -e 'bl-image-viewer /home/ash/Pictures/screenshots/%F-%H-%M-%S_scrot.png'"""
"""scrot Current Focus""","""scrot -u /home/ash/Pictures/screenshots/%F-%H-%M-%S_scrot.png -e 'bl-image-viewer /home/ash/Pictures/screenshots/%F-%H-%M-%S_scrot.png'"""
"""scrot Multi-Monitor""","""scrot -m /home/ash/Pictures/screenshots/%F-%H-%M-%S_scrot.png -e 'bl-image-viewer /home/ash/Pictures/screenshots/%F-%H-%M-%S_scrot.png'"""

^tag(imgur)
Back,^back()
"""Upload to Account""",^checkout(imgur_acct)
"""Anonymous Upload""",^checkout(imgur_anon)`

The close button on the error window works running this, whereas trying to open the submenu disables all mouse and keyboard actions. I have to wither drop to TTY and kill openbox or do a hard reboot by holding down the power button.

I only discovered this because I am running BL on Ubuntu which originally had GNOME Wayland installed but just removed it a few days ago as @johnraff and I are working to get Boron released, so not really a worry. Anyone installing Boron will get xsel included.

**Comment by johanmalm** [comment] 2023-07-03 20:51
Oh… I think I do have a partition with Ubuntu-wayland. Will try it but will have to be another evening

**Comment by hhhorb** [comment] 2023-07-03 22:01
No worries, and no rush. Good to hear from you!

**Comment by johnraff** [comment] 2023-07-05 06:25
Sorry, I've been away for a few days and only just saw this.
I can confirm the desktop freeze when - without xsel - running the scrot pipemenu from jgmenu, but not from a terminal.
The yad error box is behind the menu, but the desktop is now frozen:

![https://imgur.com/0PLwbU3.png](https://imgur.com/0PLwbU3.png)

Running from the terminal, yad can be closed, and the desktop is OK:

![https://imgur.com/8mF074k.png](https://imgur.com/8mF074k.png)

An easy way to trigger this issue is to put `yad --text='BAD'` somewhere in the code of any pipemenu. `mousepad` works too, so it looks as if opening any X window while jgmenu is running will cause the crash.

Off-Topic (just to get these recorded):

1) There's a bug in bl-imgur-upload so the missing-apps test which throws up the yad window is not actually returning '1'. Easily fixed.

2) The stream of GTK warnings about the  _:insensitive pseudo-class_ is thrown up by any X app. Maybe a tweak to the theme would fix this?

**Comment by johnraff** [comment] 2023-07-07 03:04
Further digging turned up that this issue does not occur on Debian Bullseye.
Methods here: https://forums.bunsenlabs.org/viewtopic.php?pid=128337#p128337

Also, a notify-send window does not trigger the freeze.

**Comment by mckaygerhard** [comment] 2023-11-28 13:20
umm as @johnraff  said is not related to jgmenu is related to a custom script and the underdistro.. under specific custom setup.. so i guess this is just a good tip to document but not per se a bug from jgmenu per se

**Comment by johanmalm** [comment] 2023-11-28 21:54
Good point. We like it when `jgmenu` is not at fault. Let's close this one then :smile:

**Closed by johanmalm** 2023-11-28 21:54 UTC

**Comment by mckaygerhard** [comment] 2023-12-07 13:03
i got those freeze also with lxpanel @johnraff  in debian jessie sometimes..in same way but different path but never tried to solve it, just change the panel to fbpanel and solved the issue..  i dont know if being related

**Comment by johnraff** [comment] 2023-12-08 05:22
Issues seem to be caused if a pipemenu prints out something other than the menu contents it should be.
In an ideal world:
1) Pipemenus will only print out menus, nothing else.
2) Desktops will not freeze, even if a pipemenu does output something unexpected.

**Comment by johanmalm** [comment] 2023-12-09 09:16
> i got those freeze also with lxpanel @johnraff in debian jessie sometimes..in same way but different path but never tried to solve it, just change the panel to fbpanel and solved the issue.. i dont know if being related

Was that using `lxpanel` with `jgmenu`, or just on it's own? 

@johnraff Do we have any "bad" pipemenu output that I can use to try to harden jgmenu?

**Comment by johnraff** [comment] 2023-12-10 05:30
Sure, just put any command that opens a window inside a pipemenu next to a properly formatted menu entry.
eg
```
#!/bin/sh
# test pipemenus
#x-terminal-emulator
printf '%s\n' 'Open Terminal,x-terminal-emulator'
#notify-send 'submenu created'
#x-terminal-emulator
exit
```
And put a line in prepend.csv to call it:
```
Test Pipemenu,^pipe( ~/bin/test-pipemenu )
```
It should work OK like that, but try uncommenting one of the x-terminal-emulator lines. (Any app that opens a window will do.)

A bit more detail here: https://forums.bunsenlabs.org/viewtopic.php?pid=128337#p128337
