### ISSUE TITLE
Error with widgets in archlinux.

### ISSUE THREAD

**Issue by Gilraiser** [jgmenu/jgmenu#204] opened 2023-11-01 02:15 UTC
Best regard. When I add more than one widget that run commands, all widgets run the same command as the first widget I create. What I think should happen is for each widget to independently execute the commands I assigned to them. Below I show how I configured the widgets. Thank you very much for developing useful software independent of large graphical environments.

@icon,icesh logout,150,45,150,50,,,,,,/home/user/image.png
@icon,icesh reboot,25,25,80,80,,,,,,/home/user/image02.png

**Comment by johanmalm** [comment] 2023-11-02 19:57
Hi there. I can't reproduce that.

The following works as expected (i.e. the first button launches xterm and the second sakura).

```
@icon,xterm,30,45,32,32,2,left,top,#e6e6e6 100,#444444 90,/usr/share/icons/oxygen/base/32x32/actions/bookmark-new.png
@icon,sakura,90,45,32,32,2,left,top,#e6e6e6 100,#444444 90,/usr/share/icons/oxygen/base/32x32/actions/view-list-icons.png

^tag(apps)
```

**Comment by johanmalm** [comment] 2023-11-02 19:58
Is it worth trying something different to `icesh`

**Comment by Gilraiser** [comment] 2023-11-03 07:26
Thanks for answering. I tried with openbox, the widgets worked but the last widget command is filtered to the rest of the items, it does not allow entering the submenus because the last widget command is executed with the other menu items. The widgets do work well. I'm putting the configuration files here in case you or someone else would like to help me with any mistakes I'm making. Thank you very much in advance.

**Contents of the jgmenurc file:**

_# verbosity = 0
stay_alive = 1
# persistent = 0
# hide_on_startup = 0
csv_cmd = apps
#tint2_look = 1
position_mode = ipc
# edge_snap_x = 30
terminal_exec = mate-terminal
# terminal_args = -e
# monitor = 0
# hover_delay = 100
hide_back_items = 0
columns = 2
# tabs = 120
# menu_margin_x = 0
menu_margin_y = 0
menu_width = 400
menu_height_min = 615
menu_height_max = 615
# menu_height_mode = static
menu_padding_top = 100
# menu_padding_right = 5
menu_padding_bottom = 50
# menu_padding_left = 5
menu_radius = 0
# menu_border = 0
# menu_halign = left
# menu_valign = bottom
menu_gradient_pos = top
# sub_spacing = 1
sub_padding_top = 100
# sub_padding_right = auto
# sub_padding_bottom = auto
# sub_padding_left = auto
# sub_hover_action = 1
# item_margin_x = 3
item_margin_y = 45
# item_height = 25
# item_padding_x = 4
# item_radius = 1
# item_border = 0
# item_halign = left
sep_height = 10
sep_halign = center
# sep_markup = 
font = Serif 12
# font_fallback = xtg
icon_size = 45
# icon_text_spacing = 10
# icon_norm_alpha = 100
# icon_sel_alpha = 100
icon_theme = 'Windows XP'
# icon_theme_fallback = xtg
# arrow_string =
arrow_width = 0
color_menu_bg = #2663E0
color_menu_bg_to = #438FEA
color_menu_border = #2663E0
#color_norm_bg = #D3E5FA
color_norm_fg = #000000
color_sel_bg = #2663E0
#color_sel_fg = #FFFFFF
color_sel_border = #D3E5FA
color_sep_fg = #000000
color_scroll_ind = #CCDEF4
color_title_fg = #FFFFFF
color_title_bg = #000000
# color_title_border = #000000 0
#csv_name_format = %n (%g)
#csv_single_window = 1
#csv_no_dirs = 1
csv_i18n = es
csv_no_duplicates = 1_

**Contents of my jgmenu configuration file:**

# the root-menu

Web,^root(web),/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/internet_explorer_6.png

Gráficos,^root(graficos),/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/paint.png

Multimedia,^root(multimedia),/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/windows_media_player_10.png

Accesorios,^root(accesorios),/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/tweak_ui.png

Ofimática,^root(ofimatica),/home/user/MENU-XP/office.png

Sistema,^root(sistema),/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/control_panel.png

Principal,thunar /home/user,/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/folder_options.png

Recientes,thunar recent:///,/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/recent_documents.png

My Pc,thunar computer:///,/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/my_computer.png

Buscar,catfish,/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/search.png

Salir,^root(salir),/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/power.png


^tag(web)

Volver,^back(),/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/setup_back.png

Firefox,firefox,firefox

^tag(graficos)

Volver,^back(),/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/setup_back.png

Gimp,gimp,gimp
Viewnior,viewnior,viewnior
Gpick,gpick,gpick

Inkscape,inkscape,/home/user/MENU-XP/inkscape.svg

^tag(multimedia)

Volver,^back(),/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/setup_back.png

Media Player,smplayer,smplayer

Mezclador de Sonidos del Sistema,pavucontrol,/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/audio_devices.png


^tag(sistema)

Volver,^back(),/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/setup_back.png

Consola,mate-terminal,/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/command_prompt.png

Barra de Tareas,tint2conf,/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/taskbar_and_start_menu.png

Localización de Hardware,lstopo,/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/add_new_hardware.png

Visor de Procesos,lxtask,/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/task_manager.png

Visor HTop,^term(htop),htop

Visor de Red,^term(sudo iftop),/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/network_connection.png

Visor Nload,^term(nload),/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/remote_access_service.png



^tag(ofimatica)

Volver,^back(),/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/setup_back.png

Procesador de Texto,abiword,abiword

Hoja de Cálculo,gnumeric,gnumeric

^tag(accesorios)

Volver,^back(),/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/setup_back.png

Editor de Texto,xed,/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/notepad.png

Apariencia,lxappearance,/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/appearance.png

Archivador,xarchiver,xarchiver

^tag(salir)

Volver,^back(),/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/setup_back.png

Cerrar Sesión,/home/user/.config/icewm/cerrarsesion.sh,/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/logout.png

Reinciar,/home/user/.config/icewm/reiniciar.sh,/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/restart.png

Apagar,/home/user/.config/icewm/apagar.sh,/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/power.png

@icon,,150,45,150,50,0,left,top,auto,#000000 0,/home/user/MENU-XP/image-01.png
@icon,sudo lxdm-config,25,25,80,80,0,left,top,auto,#000000 0,/home/user/MENU-XP/image-02.png
@icon,openbox --exit,80,550,40,40,0,left,top,#000000 0,#000000 0,/home/user/MENU-XP/ICONONS-HD-XP/ICONOS-HD-XP/windows_xp_icons/power.png
@rect,,196,130,201,400,0,left,top,#000000 0,#CCDEF4,
@rect,,0,130,194,400,0,left,top,#000000 0,#FFFFFF,

**Comment by johanmalm** [comment] 2023-11-04 13:14
I can't reproduce the issue.

Could we try with a common, simple setup. Could you try with the following config files and let me know if you can re-produce.

`jgmenurc`

```
menu_width = 400
menu_height_min = 400
```


`test.csv`

```
@icon,lxterminal -e 'echo 1 ; sh',10,100,10,10,0,left,top,#FF0000 50,#AAAAAA 50,
@icon,lxterminal -e 'echo 2 ; sh',30,100,10,10,0,left,top,#FF0000 50,#AAAAAA 50,
@icon,lxterminal -e 'echo 3 ; sh',50,100,10,10,0,left,top,#FF0000 50,#AAAAAA 50,

@rect,lxterminal -e 'echo 4 ; sh',10,200,10,10,0,left,top,#FF0000 50,#CCDEF4,
@rect,lxterminal -e 'echo 5 ; sh',30,200,10,10,0,left,top,#FF0000 50,#CCDEF4,
@rect,lxterminal -e 'echo 6 ; sh',50,200,10,10,0,left,top,#FF0000 50,#CCDEF4,

foo,bar,baz
```

Run with `jgmenu --simple < test.csv`

**Comment by Gilraiser** [comment] 2023-11-04 23:28
Again, thank you very much for answering. I attach a video with the results. The same thing happens, the commands in the widgets are filtered to the other elements. Maybe with a video it will be clearer what mistake I may be making or if it is a bug. Thanks, again.


https://github.com/jgmenu/jgmenu/assets/45057390/1216a773-19a7-411d-baf0-57dd3b590d91

**Comment by Gilraiser** [comment] 2023-11-05 00:37
En este video también utilizo Openbox y ArchLinux, pero en un disco duro diferente. Tratando de descartar que sea algún tema de iconos o de colores defectuosos. Sucede el mimo error.


https://github.com/jgmenu/jgmenu/assets/45057390/b98ba073-fef0-417f-9fb8-1209e27e1a7a

**Comment by johanmalm** [comment] 2023-11-06 07:08
Thank you for the videos. That makes it very clear.

I have done exactly what the videos show, but still can’t reproduce. 

This type of bug could be the result of not setting a variable or allocated to zero on definition or something like that.

Is there anything unusual about your setup? For example are you running under qemo?

Do it happen every time or just occasionally?

Next steps:

1. The easiest way is to get me to reproduce the bug. That way I should be able to pin it down quickly.
2. If that’s not possible, I could add a bunch of printf()s on a branch assuming you’re happy to clone + build that (I can give you step by step instructions). 

Step 2 is likely to take a while, but I’m keen to get to the bottom of this one if your happy to work on it together.

**Comment by Gilraiser** [comment] 2023-11-06 18:08
Hello. Best regard. Honestly, I don't think there is anything unusual in my configuration. The first video is archlinux with lxdm, icewm and openbox with the nvidia nouveau drivers. The second video is another hard drive with an even simpler installation that is just archlinux with openbox and proprietary nvidia drivers. In both videos jgmenu is launched from a titnt2 button. The same thing happens in both icewm and openbox. I'm not using any emulator, it's with real hardware and it only happens if I have at least one command in one of the widgets. I am not a programmer but I would like to help, count on my help. Thank you very much for developing this software and apologies for my English since I helped myself with a translator.

**Comment by johanmalm** [comment] 2023-11-07 19:01
I'll add some logging on a branch. Might be a few days though. Life is proving busy :smile:

**Comment by Gilraiser** [comment] 2023-11-17 00:31
Hello. I managed to compile the jgmenu-git version from ArchLinux AUR. It works perfectly. I'm not a programmer, but I suppose it would be good to keep the bug in mind in case it could be repeated in some way in a later version. Anyway, I'm going to contact the package maintainer of the official repositories through his email so he's aware of this. Thank you very much for your help, I no longer have the problem with the widgets, it works perfectly. I leave it up to you if you want to close this thread.

**Comment by johanmalm** [comment] 2023-11-17 08:00
Thanks for letting me know.

I did push a potential fix a couple of days ago, so it would be useful to understand if that made the difference.

https://github.com/jgmenu/jgmenu/commit/dd85298c4aabcf08672828a909c9345d7af129eb

I suggest not contacting the package maintainer until we’ve done some more research if you’re happy to hang on. They are likely to just want to know when it’s fixed and then want a new release.

Would you be happy to build from scratch before and at the fix above to confirm.

I can send step-by-step instructions. On arch it’s very simple. No need to install anything or run as sudo. (Just compile/run from local directory)

**Comment by Gilraiser** [comment] 2023-11-19 01:34
Hello. Ok, I would like to help.

**Comment by johanmalm** [comment] 2023-11-19 08:36
```
killall jgmenu
git clone https://github.com/jgmenu/jgmenu.git
cd jgmenu
git checkout v4.4.1
./configure
make
./jgmenu
```

Don't use `./jgmenu_run` because it'll look for binaries in `$PATH` so it'll get more complicated to workout which version you're really testing.

If the issue exists with `v4.4.1` but not with `master`, then we can conclude that we've fixed it and I'll get ready for the release of `4.4.2`.

There have not been many commits since `v4.4.1` but three of them relate to widgets.

You may need to install `gcc`, `pkg-config`, `make` and `git` for the above to work - but suspect you've already got them.

**Comment by Gilraiser** [comment] 2023-11-20 07:24
Hello. I put these two videos. In one I show the build and how it works. In the second video I show the version of git installed and how it works. The version I compiled with your instructions retains the widgets bug and the git version no longer has this bug.

https://github.com/jgmenu/jgmenu/assets/45057390/2719e13b-4f4a-4ba2-83a7-b4f319752fd4


https://github.com/jgmenu/jgmenu/assets/45057390/1047a143-eba7-4089-b408-006820aab989

I hope to be helpful.

**Comment by johanmalm** [comment] 2023-11-21 19:59
> Hello. Best regard. I put two videos where I show in the first video the github version compiled and installed with the instructions you gave me. In this way the error with the widgets persists. And in the second I show how it works with the jgmenu-git version of AUR from Archlinux, where the problem no longer appears. I hope it is helpful to everyone.

This is great. Thank you. 
That proves that the issue is fixed. 
I'll close this one and try to release a new version pretty soon.

**Closed by johanmalm** 2023-11-21 19:59 UTC
